/*
 * Lighting MLP Model Data - INT8 Quantized
 * Placeholder file - Generated by train_model.py
 *
 * Run: python prj/ai/train_model.py
 */

#ifndef LIGHTING_MODEL_DATA_H_
#define LIGHTING_MODEL_DATA_H_

#include <stdint.h>

/*
 * Model info:
 * - Input: 7 features (float32)
 * - Output: 2 values (color_temp, brightness)
 * - Size: ~4KB INT8 quantized
 * - Structure: 7 → 32 → 16 → 2
 */

/* Placeholder: actual model data will be generated by training script */
const unsigned int g_lighting_model_data_len = 0;
const alignas(16) unsigned char g_lighting_model_data[] = {
    /* Model data placeholder - run train_model.py to generate */
};

#endif /* LIGHTING_MODEL_DATA_H_ */
